management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
server:
  port: 9999
resilience4j:
  circuitbreaker:
    instances:
      backendA:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 80
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
      backendB:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 50
        failureRateThreshold: 80
        waitDurationInOpenState: 10000
        minimumNumberOfCalls: 10
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
    url: jdbc:mysql://localhost:3306/hibernate
    username: root
    password: admin1234
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        generate_statistics: true
  cache:
#    jcache:
#      config: classpath:ehcache.xml
    cache-names: simpleCache
