{{- if .Values.host }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}
              servicePort: http
            path: {{.Values.path}}(/|$)(.*)
  {{- end }}
